default: &default
  host: ''
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: denis

development:
  <<: *default
  database: HR_CRM_development

test:
  <<: *default
  database: HR_CRM_test

production:
  <<: *default
  database: HR_CRM_production
